- hosts: devops_ubuntu*
  name: Setup jenkins
  gather_facts: true
  become: true
  
  vars:
    jenkins_hostname: localhost
    jenkins_http_port: 8080
    java_packages:
      - openjdk-8-jdk
    jenkins_proxy_host: "192.168.0.141"
    jenkins_proxy_port: "10809"
    jenkins_proxy_noproxy:
      - "127.0.0.1"
      - "localhost"
      - "192.168.0.121"
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins